# Command Database
spring.datasource.command.url=jdbc:postgresql://postgres-command:5432/empl_db_command
spring.datasource.command.username=admin_1
spring.datasource.command.password=admin123

# Query Database
spring.datasource.query.url=jdbc:postgresql://postgres-query:5432/empl_db_query
spring.datasource.query.username=admin_2
spring.datasource.query.password=admin123

# Auth Database
spring.datasource.auth.url=jdbc:postgresql://postgres-Auth:5432/empl_db_auth
spring.datasource.auth.username=admin_3
spring.datasource.auth.password=admin123

# RabbitMQ
spring.rabbitmq.host=rabbitmq
spring.rabbitmq.port=5672
spring.rabbitmq.username=rabbit_admin
spring.rabbitmq.password=rabbit123

# Redis
spring.data.redis.host=redis
spring.data.redis.port=6379

jwt.secret=404E635266556A586E3272357538782F413F4428472B4B6250645367566B5970

server.port=8081